### ISSUE TITLE
Suggestion: auto pin message

### ISSUE THREAD

**Issue by Olfi01** [Olgabrezel/WWAchvBot#1]
Have the bot pin the message automatically and re-pin the old message after the game.

**Comment by Olgabrezel** [comment]
@Olfi01 I will, as soon as Telegram.Bot is up-to-date so I can get the currently pinned message by GetChat()

**Comment by Olgabrezel** [comment]
@Olgabrezel I actually did it now, with a command to define the pinned message. Still waiting for Telegram.Bot *shrug*

**Comment by Olgabrezel** [comment]
Okay I did it with a command to set the pinned message. Leaving this issue open as a reminder to change it once Telegram.Bot is updated.
